site_name: Sparrows Ideen

nav:
  - index.md
  - Spiel-Ideen:
    - Spiel-Ideen/Allgemein.md
    - Spiel-Ideen/Fangis.md
    - Spiel-Ideen/Fussball.md
    - Spiel-Ideen/Games-IRL.md
    - Spiel-Ideen/Hosensackspiele.md
    - Spiel-Ideen/Raetsel.md
    - Spiel-Ideen/Stafetten.md
    - Spiel-Ideen/Voelks.md
  - Programm-Ideen:
    - Programm-Ideen/Allgemein.md
    - Programm-Ideen/Basteln.md
    - Programm-Ideen/Bauen.md
    - Programm-Ideen/Kochen-und-Backen.md
    - Programm-Ideen/Lernen.md


theme:
  name: material
  logo: assets/cevi-wet.png
  favicon: assets/sparrows.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  language: de
  palette:
    - scheme: slate
      primary: green
      accent: indigo
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://cevi-wetzikon.ch/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/cevi.wetzikon/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ceviwetzikon



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 Cevi Wetzikon - Tweet & Shark

repo_url: https://github.com/surmatik/Sparrows-Ideen
repo_name: surmatik/Sparrows-Ideen
edit_uri: edit/main/docs/


plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true
  - git-authors
  - git-committers:
      repository: squidfunk/mkdocs-material
      branch: main
      enabled: !ENV [CI, false]
  - git-authors